//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 01:46:04 PM CEST 
//


package rs.ac.uns.ftn.xws_tim2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.xws_tim2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.xws_tim2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AllAdvertisementsRequest }
     * 
     */
    public AllAdvertisementsRequest createAllAdvertisementsRequest() {
        return new AllAdvertisementsRequest();
    }

    /**
     * Create an instance of {@link Advertisement }
     * 
     */
    public Advertisement createAdvertisement() {
        return new Advertisement();
    }

    /**
     * Create an instance of {@link EditPricelistResponse }
     * 
     */
    public EditPricelistResponse createEditPricelistResponse() {
        return new EditPricelistResponse();
    }

    /**
     * Create an instance of {@link AllAdvertisementsResponse }
     * 
     */
    public AllAdvertisementsResponse createAllAdvertisementsResponse() {
        return new AllAdvertisementsResponse();
    }

    /**
     * Create an instance of {@link AddImagesResponse }
     * 
     */
    public AddImagesResponse createAddImagesResponse() {
        return new AddImagesResponse();
    }

    /**
     * Create an instance of {@link NewPricelistResponse }
     * 
     */
    public NewPricelistResponse createNewPricelistResponse() {
        return new NewPricelistResponse();
    }

    /**
     * Create an instance of {@link DeletePricelistResponse }
     * 
     */
    public DeletePricelistResponse createDeletePricelistResponse() {
        return new DeletePricelistResponse();
    }

    /**
     * Create an instance of {@link DeleteAdvertisementResponse }
     * 
     */
    public DeleteAdvertisementResponse createDeleteAdvertisementResponse() {
        return new DeleteAdvertisementResponse();
    }

    /**
     * Create an instance of {@link AllPricelistsRequest }
     * 
     */
    public AllPricelistsRequest createAllPricelistsRequest() {
        return new AllPricelistsRequest();
    }

    /**
     * Create an instance of {@link Pricelist }
     * 
     */
    public Pricelist createPricelist() {
        return new Pricelist();
    }

    /**
     * Create an instance of {@link NewPricelistRequest }
     * 
     */
    public NewPricelistRequest createNewPricelistRequest() {
        return new NewPricelistRequest();
    }

    /**
     * Create an instance of {@link EditPricelistRequest }
     * 
     */
    public EditPricelistRequest createEditPricelistRequest() {
        return new EditPricelistRequest();
    }

    /**
     * Create an instance of {@link DeletePricelistRequest }
     * 
     */
    public DeletePricelistRequest createDeletePricelistRequest() {
        return new DeletePricelistRequest();
    }

    /**
     * Create an instance of {@link EditAdvertisementResponse }
     * 
     */
    public EditAdvertisementResponse createEditAdvertisementResponse() {
        return new EditAdvertisementResponse();
    }

    /**
     * Create an instance of {@link AllPricelistsResponse }
     * 
     */
    public AllPricelistsResponse createAllPricelistsResponse() {
        return new AllPricelistsResponse();
    }

    /**
     * Create an instance of {@link AddImagesRequest }
     * 
     */
    public AddImagesRequest createAddImagesRequest() {
        return new AddImagesRequest();
    }

    /**
     * Create an instance of {@link DeleteAdvertisementRequest }
     * 
     */
    public DeleteAdvertisementRequest createDeleteAdvertisementRequest() {
        return new DeleteAdvertisementRequest();
    }

    /**
     * Create an instance of {@link NewAdvertisementRequest }
     * 
     */
    public NewAdvertisementRequest createNewAdvertisementRequest() {
        return new NewAdvertisementRequest();
    }

    /**
     * Create an instance of {@link NewAdvertisementResponse }
     * 
     */
    public NewAdvertisementResponse createNewAdvertisementResponse() {
        return new NewAdvertisementResponse();
    }

    /**
     * Create an instance of {@link EditAdvertisementRequest }
     * 
     */
    public EditAdvertisementRequest createEditAdvertisementRequest() {
        return new EditAdvertisementRequest();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Car }
     * 
     */
    public Car createCar() {
        return new Car();
    }

    /**
     * Create an instance of {@link Review }
     * 
     */
    public Review createReview() {
        return new Review();
    }

}
